In [ ]:
a = ' Machine learning' 

In [ ]:
a

' Machine learning'

In [ ]:
b  = 10

In [ ]:
b

10

In [ ]:
print(type(b))

<class 'int'>


In [ ]:
c =  10.5

In [ ]:
c

10.5

In [ ]:
print(type(c))

<class 'float'>


In [ ]:
a,b,c,d,e=1,2,3,4,5 # we can assign a values at a time for all

In [ ]:
print(a)

1


In [ ]:
print(b)

2


In [ ]:
print(c)

3


In [ ]:
print(d)

4


In [ ]:
print(e)

5


In [ ]:
a = input("Enter value of a:")

Enter value of a:5


In [ ]:
a = input("Enter value of a:")

Enter value of a:machinelearning


In [ ]:
a = input("Enter value of a:")

Enter value of a:1.0254


In [ ]:
a = int(input(" enter the value")) # here only integer only taken

 enter the value123456789


In [ ]:
print(type(a))

<class 'int'>


In [ ]:
a = str(input(" enter the value")) # here only string only taken

 enter the valuemachine learning


In [ ]:
print(type(a))

<class 'str'>


In [ ]:
a = float(input(" enter the value")) # here only float only taken

 enter the value1.23456789


In [ ]:
print(type(a))

<class 'float'>


In [ ]:
a = int(input(" enter the value a:"))
b = int(input(" enter the value b:"))
c = a + b
print(c)


 enter the value a:10
 enter the value b:5
15


In [ ]:
a  =  2 + 5j

In [ ]:
a

(2+5j)

In [ ]:
type(a)

complex

In [ ]:
a = 'Machine Learining'

In [ ]:
print(a*10)

 Machine Learining Machine Learining Machine Learining Machine Learining Machine Learining Machine Learining Machine Learining Machine Learining Machine Learining Machine Learining


In [ ]:
print(a[0:15]) #slice of string

Machine Learini


In [ ]:
print(len(a)) # lenght of string

17


In [ ]:
print(a[1:10:3]) #here in string every  3 letter will remove between 2 & 11 letter

ai 


In [ ]:
lst = ['one',2 ,3.0,True]

In [ ]:
print(lst)

['one', 2, 3.0, True]


In [ ]:
print(type(lst[0]))  # checking type using index 

<class 'str'>


In [ ]:
print(type(lst[1]))

<class 'int'>


In [ ]:
print(type(lst[2]))

<class 'float'>


In [ ]:
print(type(lst[3]))

<class 'bool'>


In [ ]:
print(type(lst))  # type

<class 'list'>


In [ ]:
lst1 = [] #  created a empty list

In [ ]:
print(lst1)

[]


In [ ]:
 lst1.append(1)  # we can add,remove values to list because it is mutuable

In [ ]:
print(lst1)

[1]


In [ ]:
lst1.append(2)

In [ ]:
print(lst1)

[1, 2]


In [ ]:
lst1.append(3)

In [ ]:
print(lst1)

del lst1[0]

print(lst1)

[1, 2, 3]
[2, 3]


In [ ]:
print('list1 :',lst)
print('list2 :',lst1)
lst2 = lst + lst1
print(lst2)

list1 : ['one', 2, 3.0, True]
list2 : []
['one', 2, 3.0, True]


In [ ]:
tup = ('one',2,3.0,True) # created a tuple which is immutable , doesnt add and remove the values

In [ ]:
print(tup)

('one', 2, 3.0, True)


In [ ]:
lst


['one', 2, 3.0, True]

In [ ]:
tup1 = tuple(lst) # chganging list to tuple

In [ ]:
print(tup1)

('one', 2, 3.0, True)


In [ ]:
print(type(tup1))

<class 'tuple'>


In [ ]:
print(len(tup1)) # finding lenght of tuple

4


In [ ]:
st = { 1,2,3,4,5,6,7,8,9}

In [ ]:
print(st)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
print(type(st))

<class 'set'>


In [ ]:
print(len(st))

9


In [ ]:
st1 = {1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,10} #here duplicate values are not allowed in set

In [ ]:
print(st1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
lst

['one', 2, 3.0, True]

In [ ]:
st2 = set(lst) # converting list to set

In [ ]:
print(st2)

{True, 2, 3.0, 'one'}


In [ ]:
 dct = {'num1' : 'one', 'num2': 'two', 'num3' : 'three' , 'num4' : 'four', 'num5': 'five'}

In [ ]:
print(dct)

{'num1': 'one', 'num2': 'two', 'num3': 'three', 'num4': 'four', 'num5': 'five'}


In [ ]:
type(dct)

dict

In [ ]:
len(dct)

5

In [ ]:
print(dct['num1'])

one


In [ ]:
print(dct['num2'])

two


In [ ]:
 dct = {'num1' : 'one', 'num2': 'two', 'num3' : 'three' , 'num4' : 'four', 'num4': 'four'}

In [ ]:
dct #here duplicate values are not allowed 

{'num1': 'one', 'num2': 'two', 'num3': 'three', 'num4': 'four'}

In [ ]:
a = int(input('Enter value a :'))
b = int(input('Enter value b :'))
print('sum of a and b is :',a+b)
print('diff of a nad b is :', a-b)
print('multoply of a and b is :',a*b)
print('divide',a/b)

print(a**2)
print(b%10)

Enter value a :10
Enter value b :15
sum of a and b is : 25
diff of a nad b is : -5
multoply of a and b is : 150
divide 0.6666666666666666
100
5


In [ ]:
a = int(input('Enter value a :'))
b = int(input('Enter value b :'))
print('List:',lst)

print(a == b)
print(a > b)
print(a < b)
print(a !=b)
print(a is b)
print( a is not b)
print( a in lst)
print(b not in lst)

Enter value a :5
Enter value b :10
List: ['one', 2, 3.0, True]
False
False
True
True
False
True
False
True


In [ ]:
if (lst[0] == lst[1]):                                    #if-statement
  print('Both types are equal')
else:
  print('Both types are not equal')

Both types are not equal


In [ ]:
for i in range(len(lst)):                                   # for loop
  print(lst[i],type(lst[i]))

one <class 'str'>
2 <class 'int'>
3.0 <class 'float'>
True <class 'bool'>


In [ ]:
tup


('one', 2, 3.0, True)

In [ ]:
i = 0                                                         # while loop
j = len(tup)                      
while i<j:
  print(tup[i])
  i+=1


one
2
3.0
True


In [ ]:
lst

['one', 2, 3.0, True, 10]

In [ ]:
def apd(n):                                                # Functions
  a = lst.append(n)
  return a




In [ ]:
apd(10)

In [ ]:
lst

['one', 2, 3.0, True, 10]

In [ ]:
apd(15)                                 # using functions appended in list
apd(20)         
apd('string')
apd(2.0)

In [ ]:
lst

['one', 2, 3.0, True, 10, 15, 20, 'string', 2.0]

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])     # we use list to create array

In [ ]:
print(a)

[1 2 3]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = np.array((1,2,3))    # we use tuple to create
print(a)

[1 2 3]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a.shape       # no.of rows and columns

(3, 3)

In [ ]:
a = np.zeros((10,10))

In [ ]:
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
a = np.eye(3)

In [ ]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.full((5,5),1)

In [ ]:
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
a = np.random.random((3,3))

In [ ]:
print(a)

[[0.02590218 0.95121959 0.1158646 ]
 [0.42739675 0.29501699 0.46796257]
 [0.96014425 0.07154836 0.01860179]]


In [ ]:
a = np.random.randint(1,10,(5,5))

In [ ]:
print(a)

[[2 1 3 9 3]
 [6 6 9 2 3]
 [7 6 7 6 9]
 [3 2 5 7 3]
 [9 8 4 8 5]]


In [ ]:
print(a.ndim)     # finding dimensioal of matrix

2


In [ ]:
print(a.shape)

(5, 5)


In [ ]:
print(a.size)

25


In [ ]:
a = np.random.randint(1,5,(3,4))

In [ ]:
print(a)

[[3 3 2 3]
 [4 2 2 1]
 [2 1 4 2]]


In [ ]:
b = np.transpose(a)

In [ ]:
print(b)

[[3 4 2]
 [3 2 1]
 [2 2 4]
 [3 1 2]]


In [ ]:
print(b.ndim)

2


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.shape)

(3, 4)


In [ ]:
print(b.shape)

(4, 3)
